<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251218140948 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_templates (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, hidden_fields JSON NOT NULL, is_system TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE projet_employe_poste (id INT AUTO_INCREMENT NOT NULL, duree VARCHAR(255) NOT NULL, collaborateurId INT DEFAULT NULL, projetId INT DEFAULT NULL, posteId INT DEFAULT NULL, INDEX IDX_1C574496427F5D85 (collaborateurId), INDEX IDX_1C574496ACC1CB28 (projetId), INDEX IDX_1C574496F7F147C8 (posteId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE projet_preuve (id INT AUTO_INCREMENT NOT NULL, projet_preuve_libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE upload_file (id INT AUTO_INCREMENT NOT NULL, projet_preuve_id INT DEFAULT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, INDEX IDX_81BB169BA2A570E (projet_preuve_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE projet_employe_poste ADD CONSTRAINT FK_1C574496427F5D85 FOREIGN KEY (collaborateurId) REFERENCES collaborateur (collaborateurId)');
        $this->addSql('ALTER TABLE projet_employe_poste ADD CONSTRAINT FK_1C574496ACC1CB28 FOREIGN KEY (projetId) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE projet_employe_poste ADD CONSTRAINT FK_1C574496F7F147C8 FOREIGN KEY (posteId) REFERENCES poste (id)');
        $this->addSql('ALTER TABLE upload_file ADD CONSTRAINT FK_81BB169BA2A570E FOREIGN KEY (projet_preuve_id) REFERENCES projet_preuve (id)');
        $this->addSql('DROP TABLE nature_client');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appeloffres_caution_devise');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appeloffres_sourceAppelOffres');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appel_offres_devises');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appel_offres_moyen');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appel_offres_organisme');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appel_offres_participation_type');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appel_offres_pays');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_appel_offres_type');
        $this->addSql('ALTER TABLE appel_offres CHANGE appelOffresObjet appelOffresObjet VARCHAR(255) DEFAULT NULL, CHANGE appelOffresRemarque appelOffresRemarque LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC5E88A3956 FOREIGN KEY (appelOffresTypeId) REFERENCES appel_offres_type (appelOffresTypeId)');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC532DC916C FOREIGN KEY (appelOffresMoyenLivraisonId) REFERENCES moyen_livraison (moyenLivraisonId)');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC54628374B FOREIGN KEY (appelOffresPaysId) REFERENCES pays (paysId)');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC5BD4A9BF3 FOREIGN KEY (appelOffresOrganismeDemandeurId) REFERENCES organismedemandeur (organismeDemandeurId)');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC569A1BF6E FOREIGN KEY (appelOffresDevisesId) REFERENCES devises (devisesId)');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC5200FF668 FOREIGN KEY (appelOffresCautionBancaireDeviseId) REFERENCES devises (devisesId)');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC5FB56EB45 FOREIGN KEY (appelOffresTypeParticipationId) REFERENCES participationtype (participationTypeId)');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_F30A4DC5C060A87D FOREIGN KEY (sourceAppelOffresId) REFERENCES sourceappeloffres (sourceAppelOffresId)');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_appel_offres_type TO IDX_F30A4DC5E88A3956');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_appel_offres_moyen TO IDX_F30A4DC532DC916C');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_appel_offres_pays TO IDX_F30A4DC54628374B');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_appel_offres_organisme TO IDX_F30A4DC5BD4A9BF3');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_appel_offres_devises TO IDX_F30A4DC569A1BF6E');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_appel_offres_caution_devise TO IDX_F30A4DC5200FF668');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX fk_appel_offres_participation_type TO IDX_F30A4DC5FB56EB45');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_appeloffres_sourceappeloffresid TO IDX_F30A4DC5C060A87D');
        $this->addSql('ALTER TABLE appel_offres_partenaires CHANGE role role VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE appel_offres_partenaires RENAME INDEX appel_offre_id TO IDX_E10F36AEFFAF5D99');
        $this->addSql('ALTER TABLE appel_offres_partenaires RENAME INDEX partenaire_id TO IDX_E10F36AE98DE13AC');
        $this->addSql('DROP INDEX idx_appel_offres_ordre ON appel_offres_personnel_cle_appel_offres');
        $this->addSql('DROP INDEX unique_appel_offres_personnel_cle ON appel_offres_personnel_cle_appel_offres');
        $this->addSql('ALTER TABLE appel_offres_personnel_cle_appel_offres RENAME INDEX idx_appeloffres TO IDX_AE107DE8FFAF5D99');
        $this->addSql('ALTER TABLE appel_offres_personnel_cle_appel_offres RENAME INDEX idx_appeloffrespersonnelcle TO IDX_AE107DE8E19AB23');
        $this->addSql('ALTER TABLE appel_offres_type RENAME INDEX uniq_6f65dea76f65dea7 TO UNIQ_AB76F7D132A601B2');
        $this->addSql('ALTER TABLE appeloffrespersonnelcle DROP FOREIGN KEY FK_appelOffresPersonnelCle_appelOffres');
        $this->addSql('DROP INDEX IDX_appelOffresPersonnelCle_appelOffres ON appeloffrespersonnelcle');
        $this->addSql('DROP INDEX IDX_appelOffresPersonnelCle_couleurStatus ON appeloffrespersonnelcle');
        $this->addSql('ALTER TABLE appeloffrespersonnelcle DROP appelOffresId, DROP appelOffresPersonnelCleCouleurStatus');
        $this->addSql('ALTER TABLE appeloffrespersonnelcle RENAME INDEX idx_appeloffrespersonnelcle_niveauetude TO IDX_EC378CB2E6E5D946');
        $this->addSql('ALTER TABLE categorie CHANGE categorieLibelle categorieLibelle VARCHAR(255) NOT NULL, CHANGE categorieShort categorieShort VARCHAR(255) NOT NULL, CHANGE categorieCodeRef categorieCodeRef INT NOT NULL, CHANGE categorieCodeCouleur categorieCodeCouleur VARCHAR(255) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497DD634147E737F ON categorie (categorieLibelle)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497DD63464E548EA ON categorie (categorieShort)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497DD634DD113742 ON categorie (categorieCodeRef)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497DD634E1BB45B ON categorie (categorieCodeCouleur)');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_Association_23');
        $this->addSql('DROP INDEX FK_Association_23 ON client');
        $this->addSql('ALTER TABLE client DROP paysId, CHANGE clientRaisonSocial clientRaisonSocial VARCHAR(254) NOT NULL, CHANGE clientRaisonSocialShort clientRaisonSocialShort VARCHAR(254) NOT NULL, CHANGE clientAdresse clientAdresse VARCHAR(254) NOT NULL, CHANGE clientTelephone1 clientTelephone1 VARCHAR(254) NOT NULL, CHANGE clientTelephone2 clientTelephone2 VARCHAR(254) NOT NULL, CHANGE clientTelephone3 clientTelephone3 VARCHAR(254) NOT NULL, CHANGE clientEmail clientEmail VARCHAR(254) NOT NULL, CHANGE clientPersonneContact1 clientPersonneContact1 VARCHAR(254) NOT NULL, CHANGE clientPersonneContact2 clientPersonneContact2 VARCHAR(254) NOT NULL, CHANGE clientPersonneContact3 clientPersonneContact3 VARCHAR(254) NOT NULL');
        $this->addSql('ALTER TABLE client RENAME INDEX fk_association_18 TO IDX_C74404557FA12140');
        $this->addSql('CREATE INDEX IDX_E503FFCC19EB6921 ON client_pays (client_id)');
        $this->addSql('ALTER TABLE client_pays RENAME INDEX fk_pays TO IDX_E503FFCCA6E44244');
        $this->addSql('ALTER TABLE clientsecteuractivite DROP FOREIGN KEY FK_Association_244');
        $this->addSql('DROP INDEX IDX_93A254E4BEFC80CA ON clientsecteuractivite');
        $this->addSql('DROP INDEX `primary` ON clientsecteuractivite');
        $this->addSql('ALTER TABLE clientsecteuractivite CHANGE secteurActiviteId secteur_activite_id INT NOT NULL');
        $this->addSql('ALTER TABLE clientsecteuractivite ADD CONSTRAINT FK_93A254E45233A7FC FOREIGN KEY (secteur_activite_id) REFERENCES secteur_activite (secteur_activite_id)');
        $this->addSql('CREATE INDEX IDX_93A254E45233A7FC ON clientsecteuractivite (secteur_activite_id)');
        $this->addSql('ALTER TABLE clientsecteuractivite ADD PRIMARY KEY (clientId, secteur_activite_id)');
        $this->addSql('ALTER TABLE clientsecteuractivite RENAME INDEX fk_association_24 TO IDX_93A254E4EA1CE9BE');
        $this->addSql('ALTER TABLE collaborateur DROP FOREIGN KEY FK_collaborateur_appelOffresPersonnelCle');
        $this->addSql('ALTER TABLE collaborateur DROP FOREIGN KEY FK_collaborateur_nationaliteId');
        $this->addSql('ALTER TABLE collaborateur DROP FOREIGN KEY FK_collaborateur_paysId');
        $this->addSql('ALTER TABLE collaborateur CHANGE collaborateurPrenom collaborateurPrenom VARCHAR(254) DEFAULT NULL, CHANGE collaborateurNom collaborateurNom VARCHAR(254) DEFAULT NULL, CHANGE collaborateurLieuNaissance collaborateurLieuNaissance VARCHAR(254) DEFAULT NULL, CHANGE collaborateurAdresse collaborateurAdresse VARCHAR(254) DEFAULT NULL, CHANGE collaborateurEmail1 collaborateurEmail1 VARCHAR(254) DEFAULT NULL, CHANGE collaborateurEmail2 collaborateurEmail2 VARCHAR(254) DEFAULT NULL, CHANGE collaborateurTelephone1 collaborateurTelephone1 VARCHAR(254) DEFAULT NULL, CHANGE collaborateurTelephone2 collaborateurTelephone2 VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE collaborateur ADD CONSTRAINT FK_770CBCD335569A8D FOREIGN KEY (paysId) REFERENCES pays (paysId) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE collaborateur ADD CONSTRAINT FK_770CBCD36AD4B07D FOREIGN KEY (nationaliteId) REFERENCES nationalite (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE collaborateur ADD CONSTRAINT FK_770CBCD3E19AB23 FOREIGN KEY (appelOffresPersonnelCleId) REFERENCES appeloffrespersonnelcle (appelOffresPersonnelCleId) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE collaborateur RENAME INDEX fk_collaborateur_paysid TO IDX_770CBCD335569A8D');
        $this->addSql('ALTER TABLE collaborateur RENAME INDEX fk_collaborateur_nationaliteid TO IDX_770CBCD36AD4B07D');
        $this->addSql('ALTER TABLE collaborateur RENAME INDEX idx_collaborateur_appeloffrespersonnelcle TO IDX_770CBCD3E19AB23');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education DROP FOREIGN KEY FK_collaborateur_collaborateur_education_collaborateur');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education DROP FOREIGN KEY FK_collaborateur_collaborateur_education_education');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education ADD CONSTRAINT FK_797DA995427F5D85 FOREIGN KEY (collaborateurId) REFERENCES collaborateur (collaborateurId)');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education ADD CONSTRAINT FK_797DA995D12A42D1 FOREIGN KEY (collaborateurEducationId) REFERENCES collaborateureducation (collaborateurEducationId)');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education RENAME INDEX idx_collaborateurid TO IDX_797DA995427F5D85');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education RENAME INDEX idx_collaborateureducationid TO IDX_797DA995D12A42D1');
        $this->addSql('ALTER TABLE collaborateurdocuments DROP FOREIGN KEY FK_employedocuments_collaborateurId');
        $this->addSql('ALTER TABLE collaborateurdocuments ADD CONSTRAINT FK_DFE49B9147569B9F FOREIGN KEY (collaborateurDocumentsType) REFERENCES typedocument (typeDocumentId)');
        $this->addSql('ALTER TABLE collaborateurdocuments ADD CONSTRAINT FK_DFE49B91427F5D85 FOREIGN KEY (collaborateurId) REFERENCES collaborateur (collaborateurId)');
        $this->addSql('CREATE INDEX IDX_DFE49B9147569B9F ON collaborateurdocuments (collaborateurDocumentsType)');
        $this->addSql('ALTER TABLE collaborateurdocuments RENAME INDEX fk_collaborateur_documents TO IDX_DFE49B91427F5D85');
        $this->addSql('ALTER TABLE collaborateureducation DROP FOREIGN KEY FK_collaborateureducation_typeDiplome');
        $this->addSql('ALTER TABLE collaborateureducation ADD CONSTRAINT FK_A65EB7CB2DE41727 FOREIGN KEY (typeDiplomeId) REFERENCES typediplome (typeDiplomeId)');
        $this->addSql('ALTER TABLE collaborateureducation RENAME INDEX fk_collaborateureducation_typediplome TO IDX_A65EB7CB2DE41727');
        $this->addSql('ALTER TABLE continent DROP continentAcronymes');
        $this->addSql('ALTER TABLE cvlangueniveau DROP cvLangueNiveauNiveau');
        $this->addSql('ALTER TABLE devises CHANGE devisesAcronyme devisesAcronyme VARCHAR(10) DEFAULT NULL, CHANGE deviseSymbole deviseSymbole VARCHAR(3) DEFAULT NULL');
        $this->addSql('ALTER TABLE employeexperience DROP FOREIGN KEY FK_employeexperience_collaborateurId');
        $this->addSql('ALTER TABLE employeexperience CHANGE paysId paysId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE employeexperience ADD CONSTRAINT FK_89226648427F5D85 FOREIGN KEY (collaborateurId) REFERENCES collaborateur (collaborateurId)');
        $this->addSql('ALTER TABLE employeexperience RENAME INDEX employeid TO IDX_89226648427F5D85');
        $this->addSql('ALTER TABLE employeexperience RENAME INDEX paysid TO IDX_8922664835569A8D');
        $this->addSql('ALTER TABLE employelangue CHANGE employeLangueNiveauId employeLangueNiveauId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE employelangue RENAME INDEX employelangueniveauid TO IDX_547287856101996A');
        $this->addSql('ALTER TABLE lieu CHANGE lieuLibelle lieuLibelle VARCHAR(255) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F577D5918F8200D ON lieu (lieuLibelle)');
        $this->addSql('ALTER TABLE lieu RENAME INDEX fk_association_19 TO IDX_2F577D5935569A8D');
        $this->addSql('ALTER TABLE moyen_livraison CHANGE moyenLivraisonShort moyenLivraisonShort VARCHAR(10) NOT NULL');
        $this->addSql('ALTER TABLE moyen_livraison RENAME INDEX uniq_348289e9348289e9 TO UNIQ_348289E9EA3748D');
        $this->addSql('ALTER TABLE nationalite DROP nationaliteCodeISO');
        $this->addSql('ALTER TABLE natureclient CHANGE natureClientLibelle natureClientLibelle VARCHAR(254) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F07C3A042B3A93C ON natureclient (natureClientLibelle)');
        $this->addSql('ALTER TABLE niveauetude CHANGE niveauEtudeLibelle niveauEtudeLibelle VARCHAR(254) DEFAULT NULL, CHANGE niveauEtudeDescription niveauEtudeDescription VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE organismedemandeur CHANGE organismeDemandeurRaisonSocialeShort organismeDemandeurRaisonSocialeShort VARCHAR(10) NOT NULL');
        $this->addSql('ALTER TABLE organismedemandeur ADD CONSTRAINT FK_4874E99535569A8D FOREIGN KEY (paysId) REFERENCES pays (paysId) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE organismedemandeur ADD CONSTRAINT FK_4874E995B05759EF FOREIGN KEY (natureOrganismeDemendeurId) REFERENCES nature_organisme_demendeur (nature_organisme_demendeur_id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE organismedemandeur ADD CONSTRAINT FK_4874E995BEFC80CA FOREIGN KEY (secteurActiviteId) REFERENCES secteur_activite (secteur_activite_id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE organismedemandeur RENAME INDEX idx_ca856b3635569a8d TO IDX_4874E99535569A8D');
        $this->addSql('ALTER TABLE organismedemandeur RENAME INDEX idx_ca856b36b05759ef TO IDX_4874E995B05759EF');
        $this->addSql('ALTER TABLE organismedemandeur RENAME INDEX idx_ca856b36befc80ca TO IDX_4874E995BEFC80CA');
        $this->addSql('ALTER TABLE partenaire CHANGE partenaireRaisonSociale partenaireRaisonSociale VARCHAR(255) NOT NULL, CHANGE partenairePremierResponsable partenairePremierResponsable VARCHAR(255) DEFAULT NULL, CHANGE partenairePremierResponsableEmail partenairePremierResponsableEmail VARCHAR(255) DEFAULT NULL, CHANGE partenaireAdresse partenaireAdresse LONGTEXT DEFAULT NULL, CHANGE partenaireEmail partenaireEmail VARCHAR(255) DEFAULT NULL, CHANGE partenaireSiteWeb partenaireSiteWeb VARCHAR(255) DEFAULT NULL, CHANGE partenaireLinkedIn partenaireLinkedIn VARCHAR(255) DEFAULT NULL, CHANGE partenaireFacebook partenaireFacebook VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pays DROP FOREIGN KEY FK_Association_16');
        $this->addSql('ALTER TABLE pays DROP codeISO, CHANGE paysLibelle paysLibelle VARCHAR(254) NOT NULL, CHANGE paysCapitale paysCapitale VARCHAR(254) NOT NULL, CHANGE continentId continentId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pays ADD CONSTRAINT FK_349F3CAEA08155E4 FOREIGN KEY (continentId) REFERENCES continent (continentId) ON DELETE SET NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_349F3CAE23588E17 ON pays (paysLibelle)');
        $this->addSql('ALTER TABLE pays RENAME INDEX fk_association_16 TO IDX_349F3CAEA08155E4');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA96AB213CC FOREIGN KEY (lieu_id) REFERENCES lieu (lieuId)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA919EB6921 FOREIGN KEY (client_id) REFERENCES client (clientId)');
        $this->addSql('ALTER TABLE projet RENAME INDEX idx_projet_lieu TO IDX_50159CA96AB213CC');
        $this->addSql('ALTER TABLE projet RENAME INDEX idx_projet_client TO IDX_50159CA919EB6921');
        $this->addSql('ALTER TABLE projet_categorie ADD CONSTRAINT FK_6A8331E0C18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE projet_categorie ADD CONSTRAINT FK_6A8331E0BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (categorieId)');
        $this->addSql('ALTER TABLE projet_categorie RENAME INDEX idx_projet_categorie_projet TO IDX_6A8331E0C18272');
        $this->addSql('ALTER TABLE projet_categorie RENAME INDEX idx_projet_categorie_categorie TO IDX_6A8331E0BCF5E72D');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_412b81a7e7c8c4f0 TO IDX_AEA3491335569A8D');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_412b81a7d29054b2 TO IDX_AEA349136F708739');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_412b81a78f96f861 TO IDX_AEA349135097CB70');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_412b81a75601c1 TO IDX_AEA34913FE278E99');
        $this->addSql('ALTER TABLE reference RENAME INDEX uniq_reference_categorie_ordre TO uniq_ref_categorie_ordre');
        $this->addSql('ALTER TABLE reference_bailleurfond RENAME INDEX idx_f241dd3c7f3c753f TO IDX_F241DD3C1645DEA9');
        $this->addSql('ALTER TABLE reference_environnement_developpement RENAME INDEX idx_318ee0f47f3c753f TO IDX_BEB0DCE41645DEA9');
        $this->addSql('ALTER TABLE reference_environnement_developpement RENAME INDEX idx_318ee0f4d0dedb1a TO IDX_BEB0DCE462FC0129');
        $this->addSql('ALTER TABLE reference_technologie RENAME INDEX idx_91180f647f3c753f TO IDX_4BB674401645DEA9');
        $this->addSql('ALTER TABLE reference_technologie RENAME INDEX idx_91180f64d12b6af5 TO IDX_4BB67440261A27D2');
        $this->addSql('ALTER TABLE reference_methodologie RENAME INDEX idx_5981e9ad7f3c753f TO IDX_A188D6B11645DEA9');
        $this->addSql('ALTER TABLE reference_methodologie RENAME INDEX idx_5981e9addc510d3 TO IDX_A188D6B143E5E91C');
        $this->addSql('ALTER TABLE reference_role RENAME INDEX idx_24ede0c7f3c753f TO IDX_20AA72CA1645DEA9');
        $this->addSql('ALTER TABLE reference_role RENAME INDEX idx_24ede0cd60322ac TO IDX_20AA72CAD60322AC');
        $this->addSql('ALTER TABLE reference_appel_offres RENAME INDEX idx_52ed80fa7f3c753f TO IDX_D2588E321645DEA9');
        $this->addSql('ALTER TABLE reference_appel_offres RENAME INDEX idx_52ed80fafc54c42d TO IDX_D2588E325427493E');
        $this->addSql('ALTER TABLE reference_caracteristique_speciale RENAME INDEX idx_9c6297f47f3c753f TO IDX_943DFAA51645DEA9');
        $this->addSql('ALTER TABLE reference_caracteristique_speciale RENAME INDEX idx_9c6297f422e7dfdb TO IDX_943DFAA5FC91F09');
        $this->addSql('ALTER TABLE reference_collaborateur MODIFY reference_collaborateurid INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON reference_collaborateur');
        $this->addSql('ALTER TABLE reference_collaborateur ADD reference_id INT NOT NULL, ADD employePosteId INT NOT NULL, CHANGE referenceCollaborateurDuree referenceCollaborateurDuree INT DEFAULT NULL, CHANGE reference_collaborateurid referenceCollaborateurId INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE reference_collaborateur ADD CONSTRAINT FK_54F489AF1645DEA9 FOREIGN KEY (reference_id) REFERENCES reference (referenceID)');
        $this->addSql('ALTER TABLE reference_collaborateur ADD CONSTRAINT FK_54F489AFAF59822E FOREIGN KEY (employePosteId) REFERENCES employeposte (employePosteId)');
        $this->addSql('CREATE INDEX IDX_54F489AF1645DEA9 ON reference_collaborateur (reference_id)');
        $this->addSql('CREATE INDEX IDX_54F489AFAF59822E ON reference_collaborateur (employePosteId)');
        $this->addSql('ALTER TABLE reference_collaborateur ADD PRIMARY KEY (referenceCollaborateurId)');
        $this->addSql('ALTER TABLE referencecaracteristiquespeciale CHANGE referenceCaracteristiqueSpecialeTitre referenceCaracteristiqueSpecialeTitre VARCHAR(255) DEFAULT NULL, CHANGE referenceCaracteristiqueSpecialeDescription referenceCaracteristiqueSpecialeDescription VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale DROP FOREIGN KEY FK_reference_referencecaracteristiquespeciale_car');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale DROP FOREIGN KEY FK_reference_referencecaracteristiquespeciale_ref');
        $this->addSql('DROP INDEX `primary` ON referencereferencecaracteristiquespeciale');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale ADD CONSTRAINT FK_75746BB54409B90 FOREIGN KEY (referenceCaracteristiqueSpecialeId) REFERENCES referencecaracteristiquespeciale (referenceCaracteristiqueSpecialeId)');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale ADD CONSTRAINT FK_75746BB57F3C753F FOREIGN KEY (referenceID) REFERENCES reference (referenceID)');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale ADD PRIMARY KEY (referenceCaracteristiqueSpecialeId, referenceID)');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale RENAME INDEX idx_reference_referencecaracteristiquespeciale_car TO IDX_75746BB54409B90');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale RENAME INDEX idx_reference_referencecaracteristiquespeciale_ref TO IDX_75746BB57F3C753F');
        $this->addSql('ALTER TABLE referencedocuments CHANGE typeDocumentId typeDocumentId INT DEFAULT NULL, CHANGE referenceID referenceID INT DEFAULT NULL, CHANGE referenceDocumentsLibelle referenceDocumentsLibelle VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE referencedocuments RENAME INDEX fk_association_15 TO IDX_547A6C97E8B2CC08');
        $this->addSql('ALTER TABLE referencedocuments RENAME INDEX fk_association_4 TO IDX_547A6C977F3C753F');
        $this->addSql('ALTER TABLE role CHANGE roleLibelle roleLibelle VARCHAR(255) DEFAULT NULL, CHANGE roleShort roleShort VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX AK_Identifiant_1 ON secteur_activite');
        $this->addSql('DROP INDEX AK_Identifiant_2 ON secteur_activite');
        $this->addSql('ALTER TABLE secteur_activite CHANGE secteurActiviteLibelle secteurActiviteLibelle VARCHAR(255) NOT NULL, CHANGE secteurActiviteDescription secteurActiviteDescription LONGTEXT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5CD9BFE1FAB72483 ON secteur_activite (secteurActiviteLibelle)');
        $this->addSql('ALTER TABLE situationfamiliale CHANGE situationFamilialeLibelle situationFamilialeLibelle VARCHAR(254) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB87AFF6910843DB ON situationfamiliale (situationFamilialeLibelle)');
        $this->addSql('ALTER TABLE technologie CHANGE referenceTechnologieDescription referenceTechnologieDescription TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE typedocument CHANGE typeDocumentLibelle typeDocumentLibelle VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(180) NOT NULL, CHANGE username username VARCHAR(180) NOT NULL, CHANGE roles roles JSON NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE reset_token reset_token VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE nature_client (id INT AUTO_INCREMENT NOT NULL, nature_client VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_F348A682F348A682 (nature_client), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE projet_employe_poste DROP FOREIGN KEY FK_1C574496427F5D85');
        $this->addSql('ALTER TABLE projet_employe_poste DROP FOREIGN KEY FK_1C574496ACC1CB28');
        $this->addSql('ALTER TABLE projet_employe_poste DROP FOREIGN KEY FK_1C574496F7F147C8');
        $this->addSql('ALTER TABLE upload_file DROP FOREIGN KEY FK_81BB169BA2A570E');
        $this->addSql('DROP TABLE project_templates');
        $this->addSql('DROP TABLE projet_employe_poste');
        $this->addSql('DROP TABLE projet_preuve');
        $this->addSql('DROP TABLE upload_file');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC5E88A3956');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC532DC916C');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC54628374B');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC5BD4A9BF3');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC569A1BF6E');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC5200FF668');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC5FB56EB45');
        $this->addSql('ALTER TABLE appel_offres DROP FOREIGN KEY FK_F30A4DC5C060A87D');
        $this->addSql('ALTER TABLE appel_offres CHANGE appelOffresObjet appelOffresObjet VARCHAR(500) DEFAULT NULL, CHANGE appelOffresRemarque appelOffresRemarque TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appeloffres_caution_devise FOREIGN KEY (appelOffresCautionBancaireDeviseId) REFERENCES devises (devisesId) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appeloffres_sourceAppelOffres FOREIGN KEY (sourceAppelOffresId) REFERENCES sourceappeloffres (sourceAppelOffresId) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appel_offres_devises FOREIGN KEY (appelOffresDevisesId) REFERENCES devises (devisesId) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appel_offres_moyen FOREIGN KEY (appelOffresMoyenLivraisonId) REFERENCES moyen_livraison (moyenLivraisonId) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appel_offres_organisme FOREIGN KEY (appelOffresOrganismeDemandeurId) REFERENCES organismedemandeur (organismeDemandeurId) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appel_offres_participation_type FOREIGN KEY (appelOffresTypeParticipationId) REFERENCES participationtype (participationTypeId) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appel_offres_pays FOREIGN KEY (appelOffresPaysId) REFERENCES pays (paysId) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres ADD CONSTRAINT FK_appel_offres_type FOREIGN KEY (appelOffresTypeId) REFERENCES appel_offres_type (appelOffresTypeId) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc5fb56eb45 TO FK_appel_offres_participation_type');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc5200ff668 TO IDX_appel_offres_caution_devise');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc569a1bf6e TO IDX_appel_offres_devises');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc532dc916c TO IDX_appel_offres_moyen');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc5bd4a9bf3 TO IDX_appel_offres_organisme');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc54628374b TO IDX_appel_offres_pays');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc5e88a3956 TO IDX_appel_offres_type');
        $this->addSql('ALTER TABLE appel_offres RENAME INDEX idx_f30a4dc5c060a87d TO IDX_appeloffres_sourceAppelOffresId');
        $this->addSql('ALTER TABLE appel_offres_partenaires CHANGE role role VARCHAR(50) DEFAULT \'Partenaire simple\' NOT NULL');
        $this->addSql('ALTER TABLE appel_offres_partenaires RENAME INDEX idx_e10f36aeffaf5d99 TO appel_offre_id');
        $this->addSql('ALTER TABLE appel_offres_partenaires RENAME INDEX idx_e10f36ae98de13ac TO partenaire_id');
        $this->addSql('CREATE INDEX idx_appel_offres_ordre ON appel_offres_personnel_cle_appel_offres (appelOffresId, ordreAffichage)');
        $this->addSql('CREATE UNIQUE INDEX unique_appel_offres_personnel_cle ON appel_offres_personnel_cle_appel_offres (appelOffresId, appelOffresPersonnelCleId)');
        $this->addSql('ALTER TABLE appel_offres_personnel_cle_appel_offres RENAME INDEX idx_ae107de8ffaf5d99 TO IDX_appelOffres');
        $this->addSql('ALTER TABLE appel_offres_personnel_cle_appel_offres RENAME INDEX idx_ae107de8e19ab23 TO IDX_appelOffresPersonnelCle');
        $this->addSql('ALTER TABLE appel_offres_type RENAME INDEX uniq_ab76f7d132a601b2 TO UNIQ_6F65DEA76F65DEA7');
        $this->addSql('ALTER TABLE appeloffrespersonnelcle ADD appelOffresId INT DEFAULT NULL, ADD appelOffresPersonnelCleCouleurStatus VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE appeloffrespersonnelcle ADD CONSTRAINT FK_appelOffresPersonnelCle_appelOffres FOREIGN KEY (appelOffresId) REFERENCES appel_offres (appelOffresId) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_appelOffresPersonnelCle_appelOffres ON appeloffrespersonnelcle (appelOffresId)');
        $this->addSql('CREATE INDEX IDX_appelOffresPersonnelCle_couleurStatus ON appeloffrespersonnelcle (appelOffresPersonnelCleCouleurStatus)');
        $this->addSql('ALTER TABLE appeloffrespersonnelcle RENAME INDEX idx_ec378cb2e6e5d946 TO IDX_appelOffresPersonnelCle_niveauEtude');
        $this->addSql('DROP INDEX UNIQ_497DD634147E737F ON categorie');
        $this->addSql('DROP INDEX UNIQ_497DD63464E548EA ON categorie');
        $this->addSql('DROP INDEX UNIQ_497DD634DD113742 ON categorie');
        $this->addSql('DROP INDEX UNIQ_497DD634E1BB45B ON categorie');
        $this->addSql('ALTER TABLE categorie CHANGE categorieLibelle categorieLibelle VARCHAR(254) DEFAULT NULL, CHANGE categorieShort categorieShort VARCHAR(254) DEFAULT NULL, CHANGE categorieCodeRef categorieCodeRef INT DEFAULT NULL, CHANGE categorieCodeCouleur categorieCodeCouleur VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE client ADD paysId INT DEFAULT NULL, CHANGE clientRaisonSocial clientRaisonSocial VARCHAR(254) DEFAULT NULL, CHANGE clientRaisonSocialShort clientRaisonSocialShort VARCHAR(254) DEFAULT NULL, CHANGE clientAdresse clientAdresse VARCHAR(254) DEFAULT NULL, CHANGE clientTelephone1 clientTelephone1 VARCHAR(254) DEFAULT NULL, CHANGE clientTelephone2 clientTelephone2 VARCHAR(254) DEFAULT NULL, CHANGE clientTelephone3 clientTelephone3 VARCHAR(254) DEFAULT NULL, CHANGE clientEmail clientEmail VARCHAR(254) DEFAULT NULL, CHANGE clientPersonneContact1 clientPersonneContact1 VARCHAR(254) DEFAULT NULL, CHANGE clientPersonneContact2 clientPersonneContact2 VARCHAR(254) DEFAULT NULL, CHANGE clientPersonneContact3 clientPersonneContact3 VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_Association_23 FOREIGN KEY (paysId) REFERENCES pays (paysId) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX FK_Association_23 ON client (paysId)');
        $this->addSql('ALTER TABLE client RENAME INDEX idx_c74404557fa12140 TO FK_Association_18');
        $this->addSql('ALTER TABLE client_pays DROP FOREIGN KEY FK_E503FFCC19EB6921');
        $this->addSql('ALTER TABLE client_pays DROP FOREIGN KEY FK_E503FFCCA6E44244');
        $this->addSql('DROP INDEX IDX_E503FFCC19EB6921 ON client_pays');
        $this->addSql('ALTER TABLE client_pays RENAME INDEX idx_e503ffcca6e44244 TO FK_PAYS');
        $this->addSql('ALTER TABLE clientsecteuractivite DROP FOREIGN KEY FK_93A254E45233A7FC');
        $this->addSql('DROP INDEX IDX_93A254E45233A7FC ON clientsecteuractivite');
        $this->addSql('DROP INDEX `PRIMARY` ON clientsecteuractivite');
        $this->addSql('ALTER TABLE clientsecteuractivite CHANGE secteur_activite_id secteurActiviteId INT NOT NULL');
        $this->addSql('ALTER TABLE clientsecteuractivite ADD CONSTRAINT FK_Association_244 FOREIGN KEY (secteurActiviteId) REFERENCES secteur_activite (secteur_activite_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_93A254E4BEFC80CA ON clientsecteuractivite (secteurActiviteId)');
        $this->addSql('ALTER TABLE clientsecteuractivite ADD PRIMARY KEY (secteurActiviteId, clientId)');
        $this->addSql('ALTER TABLE clientsecteuractivite RENAME INDEX idx_93a254e4ea1ce9be TO FK_Association_24');
        $this->addSql('ALTER TABLE collaborateur DROP FOREIGN KEY FK_770CBCD335569A8D');
        $this->addSql('ALTER TABLE collaborateur DROP FOREIGN KEY FK_770CBCD36AD4B07D');
        $this->addSql('ALTER TABLE collaborateur DROP FOREIGN KEY FK_770CBCD3E19AB23');
        $this->addSql('ALTER TABLE collaborateur CHANGE collaborateurPrenom collaborateurPrenom VARCHAR(50) DEFAULT NULL, CHANGE collaborateurNom collaborateurNom VARCHAR(50) DEFAULT NULL, CHANGE collaborateurLieuNaissance collaborateurLieuNaissance VARCHAR(100) DEFAULT NULL, CHANGE collaborateurAdresse collaborateurAdresse VARCHAR(100) DEFAULT NULL, CHANGE collaborateurEmail1 collaborateurEmail1 VARCHAR(100) DEFAULT NULL, CHANGE collaborateurEmail2 collaborateurEmail2 VARCHAR(100) DEFAULT NULL, CHANGE collaborateurTelephone1 collaborateurTelephone1 VARCHAR(50) DEFAULT NULL, CHANGE collaborateurTelephone2 collaborateurTelephone2 VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE collaborateur ADD CONSTRAINT FK_collaborateur_appelOffresPersonnelCle FOREIGN KEY (appelOffresPersonnelCleId) REFERENCES appeloffrespersonnelcle (appelOffresPersonnelCleId) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE collaborateur ADD CONSTRAINT FK_collaborateur_nationaliteId FOREIGN KEY (nationaliteId) REFERENCES nationalite (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE collaborateur ADD CONSTRAINT FK_collaborateur_paysId FOREIGN KEY (paysId) REFERENCES pays (paysId) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE collaborateur RENAME INDEX idx_770cbcd36ad4b07d TO FK_collaborateur_nationaliteId');
        $this->addSql('ALTER TABLE collaborateur RENAME INDEX idx_770cbcd335569a8d TO FK_collaborateur_paysId');
        $this->addSql('ALTER TABLE collaborateur RENAME INDEX idx_770cbcd3e19ab23 TO IDX_collaborateur_appelOffresPersonnelCle');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education DROP FOREIGN KEY FK_797DA995427F5D85');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education DROP FOREIGN KEY FK_797DA995D12A42D1');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education ADD CONSTRAINT FK_collaborateur_collaborateur_education_collaborateur FOREIGN KEY (collaborateurId) REFERENCES collaborateur (collaborateurId) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education ADD CONSTRAINT FK_collaborateur_collaborateur_education_education FOREIGN KEY (collaborateurEducationId) REFERENCES collaborateureducation (collaborateurEducationId) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education RENAME INDEX idx_797da995d12a42d1 TO IDX_collaborateurEducationId');
        $this->addSql('ALTER TABLE collaborateur_collaborateur_education RENAME INDEX idx_797da995427f5d85 TO IDX_collaborateurId');
        $this->addSql('ALTER TABLE collaborateurdocuments DROP FOREIGN KEY FK_DFE49B9147569B9F');
        $this->addSql('ALTER TABLE collaborateurdocuments DROP FOREIGN KEY FK_DFE49B91427F5D85');
        $this->addSql('DROP INDEX IDX_DFE49B9147569B9F ON collaborateurdocuments');
        $this->addSql('ALTER TABLE collaborateurdocuments ADD CONSTRAINT FK_employedocuments_collaborateurId FOREIGN KEY (collaborateurId) REFERENCES collaborateur (collaborateurId) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE collaborateurdocuments RENAME INDEX idx_dfe49b91427f5d85 TO FK_collaborateur_documents');
        $this->addSql('ALTER TABLE collaborateureducation DROP FOREIGN KEY FK_A65EB7CB2DE41727');
        $this->addSql('ALTER TABLE collaborateureducation ADD CONSTRAINT FK_collaborateureducation_typeDiplome FOREIGN KEY (typeDiplomeId) REFERENCES typediplome (typeDiplomeId) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE collaborateureducation RENAME INDEX idx_a65eb7cb2de41727 TO FK_collaborateureducation_typeDiplome');
        $this->addSql('ALTER TABLE continent ADD continentAcronymes VARCHAR(2) DEFAULT NULL');
        $this->addSql('ALTER TABLE cvlangueniveau ADD cvLangueNiveauNiveau VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE devises CHANGE devisesAcronyme devisesAcronyme VARCHAR(254) DEFAULT NULL, CHANGE deviseSymbole deviseSymbole VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE employeexperience DROP FOREIGN KEY FK_89226648427F5D85');
        $this->addSql('ALTER TABLE employeexperience CHANGE paysId paysId INT NOT NULL');
        $this->addSql('ALTER TABLE employeexperience ADD CONSTRAINT FK_employeexperience_collaborateurId FOREIGN KEY (collaborateurId) REFERENCES collaborateur (collaborateurId) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employeexperience RENAME INDEX idx_89226648427f5d85 TO employeId');
        $this->addSql('ALTER TABLE employeexperience RENAME INDEX idx_8922664835569a8d TO paysId');
        $this->addSql('ALTER TABLE employelangue CHANGE employeLangueNiveauId employeLangueNiveauId INT NOT NULL');
        $this->addSql('ALTER TABLE employelangue RENAME INDEX idx_547287856101996a TO employeLangueNiveauId');
        $this->addSql('DROP INDEX UNIQ_2F577D5918F8200D ON lieu');
        $this->addSql('ALTER TABLE lieu CHANGE lieuLibelle lieuLibelle VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE lieu RENAME INDEX idx_2f577d5935569a8d TO FK_Association_19');
        $this->addSql('ALTER TABLE moyen_livraison CHANGE moyenLivraisonShort moyenLivraisonShort VARCHAR(10) DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE moyen_livraison RENAME INDEX uniq_348289e9ea3748d TO UNIQ_348289E9348289E9');
        $this->addSql('ALTER TABLE nationalite ADD nationaliteCodeISO VARCHAR(2) DEFAULT NULL');
        $this->addSql('DROP INDEX UNIQ_2F07C3A042B3A93C ON natureclient');
        $this->addSql('ALTER TABLE natureclient CHANGE natureClientLibelle natureClientLibelle VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE niveauetude CHANGE niveauEtudeLibelle niveauEtudeLibelle VARCHAR(100) DEFAULT NULL, CHANGE niveauEtudeDescription niveauEtudeDescription VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE organismedemandeur DROP FOREIGN KEY FK_4874E99535569A8D');
        $this->addSql('ALTER TABLE organismedemandeur DROP FOREIGN KEY FK_4874E995B05759EF');
        $this->addSql('ALTER TABLE organismedemandeur DROP FOREIGN KEY FK_4874E995BEFC80CA');
        $this->addSql('ALTER TABLE organismedemandeur CHANGE organismeDemandeurRaisonSocialeShort organismeDemandeurRaisonSocialeShort VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE organismedemandeur RENAME INDEX idx_4874e99535569a8d TO IDX_CA856B3635569A8D');
        $this->addSql('ALTER TABLE organismedemandeur RENAME INDEX idx_4874e995b05759ef TO IDX_CA856B36B05759EF');
        $this->addSql('ALTER TABLE organismedemandeur RENAME INDEX idx_4874e995befc80ca TO IDX_CA856B36BEFC80CA');
        $this->addSql('ALTER TABLE partenaire CHANGE partenaireRaisonSociale partenaireRaisonSociale VARCHAR(100) NOT NULL, CHANGE partenairePremierResponsable partenairePremierResponsable VARCHAR(100) DEFAULT NULL, CHANGE partenairePremierResponsableEmail partenairePremierResponsableEmail VARCHAR(100) DEFAULT NULL, CHANGE partenaireAdresse partenaireAdresse TEXT DEFAULT NULL, CHANGE partenaireEmail partenaireEmail VARCHAR(100) DEFAULT NULL, CHANGE partenaireSiteWeb partenaireSiteWeb VARCHAR(100) DEFAULT NULL, CHANGE partenaireLinkedIn partenaireLinkedIn VARCHAR(100) DEFAULT NULL, CHANGE partenaireFacebook partenaireFacebook VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE pays DROP FOREIGN KEY FK_349F3CAEA08155E4');
        $this->addSql('DROP INDEX UNIQ_349F3CAE23588E17 ON pays');
        $this->addSql('ALTER TABLE pays ADD codeISO VARCHAR(2) DEFAULT NULL, CHANGE paysLibelle paysLibelle VARCHAR(254) DEFAULT NULL, CHANGE paysCapitale paysCapitale VARCHAR(254) DEFAULT NULL, CHANGE continentId continentId INT NOT NULL');
        $this->addSql('ALTER TABLE pays ADD CONSTRAINT FK_Association_16 FOREIGN KEY (continentId) REFERENCES continent (continentId) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE pays RENAME INDEX idx_349f3caea08155e4 TO FK_Association_16');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA96AB213CC');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA919EB6921');
        $this->addSql('ALTER TABLE projet RENAME INDEX idx_50159ca919eb6921 TO IDX_projet_client');
        $this->addSql('ALTER TABLE projet RENAME INDEX idx_50159ca96ab213cc TO IDX_projet_lieu');
        $this->addSql('ALTER TABLE projet_categorie DROP FOREIGN KEY FK_6A8331E0C18272');
        $this->addSql('ALTER TABLE projet_categorie DROP FOREIGN KEY FK_6A8331E0BCF5E72D');
        $this->addSql('ALTER TABLE projet_categorie RENAME INDEX idx_6a8331e0bcf5e72d TO IDX_projet_categorie_categorie');
        $this->addSql('ALTER TABLE projet_categorie RENAME INDEX idx_6a8331e0c18272 TO IDX_projet_categorie_projet');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_aea34913fe278e99 TO IDX_412B81A75601C1');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_aea349135097cb70 TO IDX_412B81A78F96F861');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_aea349136f708739 TO IDX_412B81A7D29054B2');
        $this->addSql('ALTER TABLE reference RENAME INDEX idx_aea3491335569a8d TO IDX_412B81A7E7C8C4F0');
        $this->addSql('ALTER TABLE reference RENAME INDEX uniq_ref_categorie_ordre TO uniq_reference_categorie_ordre');
        $this->addSql('ALTER TABLE reference_appel_offres RENAME INDEX idx_d2588e321645dea9 TO IDX_52ED80FA7F3C753F');
        $this->addSql('ALTER TABLE reference_appel_offres RENAME INDEX idx_d2588e325427493e TO IDX_52ED80FAFC54C42D');
        $this->addSql('ALTER TABLE reference_bailleurfond RENAME INDEX idx_f241dd3c1645dea9 TO IDX_F241DD3C7F3C753F');
        $this->addSql('ALTER TABLE reference_caracteristique_speciale RENAME INDEX idx_943dfaa5fc91f09 TO IDX_9C6297F422E7DFDB');
        $this->addSql('ALTER TABLE reference_caracteristique_speciale RENAME INDEX idx_943dfaa51645dea9 TO IDX_9C6297F47F3C753F');
        $this->addSql('ALTER TABLE reference_collaborateur MODIFY referenceCollaborateurId INT NOT NULL');
        $this->addSql('ALTER TABLE reference_collaborateur DROP FOREIGN KEY FK_54F489AF1645DEA9');
        $this->addSql('ALTER TABLE reference_collaborateur DROP FOREIGN KEY FK_54F489AFAF59822E');
        $this->addSql('DROP INDEX IDX_54F489AF1645DEA9 ON reference_collaborateur');
        $this->addSql('DROP INDEX IDX_54F489AFAF59822E ON reference_collaborateur');
        $this->addSql('DROP INDEX `PRIMARY` ON reference_collaborateur');
        $this->addSql('ALTER TABLE reference_collaborateur DROP reference_id, DROP employePosteId, CHANGE referenceCollaborateurDuree referenceCollaborateurDuree DATE DEFAULT NULL, CHANGE referenceCollaborateurId reference_collaborateurid INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE reference_collaborateur ADD PRIMARY KEY (reference_collaborateurid)');
        $this->addSql('ALTER TABLE reference_environnement_developpement RENAME INDEX idx_beb0dce41645dea9 TO IDX_318EE0F47F3C753F');
        $this->addSql('ALTER TABLE reference_environnement_developpement RENAME INDEX idx_beb0dce462fc0129 TO IDX_318EE0F4D0DEDB1A');
        $this->addSql('ALTER TABLE reference_methodologie RENAME INDEX idx_a188d6b11645dea9 TO IDX_5981E9AD7F3C753F');
        $this->addSql('ALTER TABLE reference_methodologie RENAME INDEX idx_a188d6b143e5e91c TO IDX_5981E9ADDC510D3');
        $this->addSql('ALTER TABLE reference_role RENAME INDEX idx_20aa72ca1645dea9 TO IDX_24EDE0C7F3C753F');
        $this->addSql('ALTER TABLE reference_role RENAME INDEX idx_20aa72cad60322ac TO IDX_24EDE0CD60322AC');
        $this->addSql('ALTER TABLE reference_technologie RENAME INDEX idx_4bb674401645dea9 TO IDX_91180F647F3C753F');
        $this->addSql('ALTER TABLE reference_technologie RENAME INDEX idx_4bb67440261a27d2 TO IDX_91180F64D12B6AF5');
        $this->addSql('ALTER TABLE referencecaracteristiquespeciale CHANGE referenceCaracteristiqueSpecialeTitre referenceCaracteristiqueSpecialeTitre VARCHAR(100) DEFAULT NULL, CHANGE referenceCaracteristiqueSpecialeDescription referenceCaracteristiqueSpecialeDescription VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE referencedocuments CHANGE referenceDocumentsLibelle referenceDocumentsLibelle VARCHAR(254) DEFAULT NULL, CHANGE typeDocumentId typeDocumentId INT NOT NULL, CHANGE referenceID referenceID INT NOT NULL');
        $this->addSql('ALTER TABLE referencedocuments RENAME INDEX idx_547a6c97e8b2cc08 TO FK_Association_15');
        $this->addSql('ALTER TABLE referencedocuments RENAME INDEX idx_547a6c977f3c753f TO FK_Association_4');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale DROP FOREIGN KEY FK_75746BB54409B90');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale DROP FOREIGN KEY FK_75746BB57F3C753F');
        $this->addSql('DROP INDEX `PRIMARY` ON referencereferencecaracteristiquespeciale');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale ADD CONSTRAINT FK_reference_referencecaracteristiquespeciale_car FOREIGN KEY (referenceCaracteristiqueSpecialeId) REFERENCES referencecaracteristiquespeciale (referenceCaracteristiqueSpecialeId) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale ADD CONSTRAINT FK_reference_referencecaracteristiquespeciale_ref FOREIGN KEY (referenceID) REFERENCES reference (referenceID) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale ADD PRIMARY KEY (referenceID, referenceCaracteristiqueSpecialeId)');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale RENAME INDEX idx_75746bb54409b90 TO IDX_reference_referencecaracteristiquespeciale_car');
        $this->addSql('ALTER TABLE referencereferencecaracteristiquespeciale RENAME INDEX idx_75746bb57f3c753f TO IDX_reference_referencecaracteristiquespeciale_ref');
        $this->addSql('ALTER TABLE role CHANGE roleLibelle roleLibelle VARCHAR(254) DEFAULT NULL, CHANGE roleShort roleShort VARCHAR(254) DEFAULT NULL');
        $this->addSql('DROP INDEX UNIQ_5CD9BFE1FAB72483 ON secteur_activite');
        $this->addSql('ALTER TABLE secteur_activite CHANGE secteurActiviteLibelle secteurActiviteLibelle VARCHAR(254) DEFAULT NULL, CHANGE secteurActiviteDescription secteurActiviteDescription VARCHAR(254) DEFAULT NULL');
        $this->addSql('CREATE INDEX AK_Identifiant_1 ON secteur_activite (secteur_activite_id)');
        $this->addSql('CREATE INDEX AK_Identifiant_2 ON secteur_activite (secteurActiviteDescription)');
        $this->addSql('DROP INDEX UNIQ_EB87AFF6910843DB ON situationfamiliale');
        $this->addSql('ALTER TABLE situationfamiliale CHANGE situationFamilialeLibelle situationFamilialeLibelle VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE technologie CHANGE referenceTechnologieDescription referenceTechnologieDescription VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE typedocument CHANGE typeDocumentLibelle typeDocumentLibelle VARCHAR(254) DEFAULT NULL');
        $this->addSql('ALTER TABLE `user` CHANGE email email VARCHAR(180) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE username username VARCHAR(180) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE roles roles LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE password password VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE reset_token reset_token VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
    }
}
