parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    app.frontend_url: '%env(FRONTEND_URL)%'
services:
    # default configuration for services in *this* file
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle: ~
    App\Controller\Api\UserController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $userRepository: '@App\Repository\UserRepository'
            $passwordHasher: '@security.user_password_hasher'
    Knp\Snappy\Pdf:
        arguments: ['%knp_snappy.pdf.binary%']
    App\Controller\Api\RapportController:
        arguments:
            $projetRepository: '@App\Repository\ProjetRepository'
            $snappy: '@knp_snappy.pdf'        
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualifiead class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Command\CreateAdminUserCommand:
        tags:
            - { name: 'console.command' }

    # Listener pour les erreurs JWT
    App\EventListener\JWTInvalidListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }